services:

  api:
    image: sistemaventas-api
    container_name: sistemaventas-api

    build:
      context: .
      dockerfile: src/SistemaVentas.Api/Dockerfile

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__SistemaVentas: "Server=sqlserver;Database=SistemaVentas;User Id=sa;Password=Password123!;TrustServerCertificate=True;"

    depends_on:
      - sqlserver

    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sistemaventas-sql

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Password123!"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql
      - D:\back_sql:/var/opt/mssql/backup

    restart: unless-stopped

volumes:
  sqlserver_data: